### PR TITLE
LSTM

### PR DESCRIPTION
**Pull request by jramapuram**
Tasks:
- [x] Forward Pass
- [ ] Backward Pass
- [ ] Recurrent Network
- [ ] Tests

### CODE REVIEW

**Comment by pavanky** [comment]
@jramapuram I updated master to separate weights and biases. Can you pull in the changes to update your PR?

**Comment by pavanky** [comment]
Can you also consider adding a simple test or example to the TODO list ?

**Comment by jramapuram** [comment]
Sure thing. Will update the changes soon.

**Comment by pavanky** [comment]
@jramapuram I am closing this issue. It'd be great if you can use the new setup to implement RNNs and LSTMs.

If you are interested in this please let me know.

**Comment by jramapuram** [comment]
@pavanky : I would love to do this still. However, if you are going to jump on this feel free. I am currently rather busy till Sept with my internship. I'll post updates here in case I am going to start it.

**Comment by pavanky** [comment]
@jramapuram may be continue the conversation here: https://github.com/arrayfire/arrayfire-ml/issues/20

**Pull request closed without merging**
